const accounts = [
    {
        firstName: 'Sanji',
        lastName: 'Vinsmoke',
        location: 'Paris, France',
        activity: 'Taekwondo',
        sex: 'Male',
        imgUrl: '/images/pfp/sanji.png',
        price: 50,
        bio: "I, Sanji, the suave chef of the Straw Hat Pirates, hail from the North Blue. Raised in the Baratie restaurant, my dream is to discover the legendary All Blue, where fish from every ocean converge. My kicks are my forte, and my chivalrous nature led me to join the Straw Hat crew, pursuing a sea of culinary adventures and excitement.",
        monday: "7am-12pm",
        tuesday: "3pm-8pm",
        wednesday: "None",
        thursday: "8am-1pm",
        friday: "8am-4pm",
        saturday: "None",
        sunday: "None"
    },
    {
        firstName: 'Tony Tony',
        lastName: 'Chopper',
        location: 'Montreal, Canada',
        activity: 'MMA',
        sex: 'Male',
        imgUrl: '/images/pfp/chopper.png',
        price: 50,
        bio: "Tony Tony Chopper, the Straw Hat Pirates' doctor and a reindeer who ate the Human-Human Fruit. I'm from Drum Island, where I faced discrimination for being different. Thanks to Dr. Hiluluk and Dr. Kureha, I pursued medicine and joined the Straw Hats. My dream is to cure any illness and make friends around the world. With my medical skills and the power of my Devil Fruit, I'm determined to heal and protect my nakama!",
        monday: "8am-1pm",
        tuesday: "4pm-9pm",
        wednesday: "3pm-7pm",
        thursday: "7am-12pm",
        friday: "None",
        saturday: "9am-2pm",
        sunday: "None"
    },
    {
        firstName: 'Trafalgar D.',
        lastName: 'Law',
        location: 'Toluca, Mexico',
        activity: 'Taekwondo',
        sex: 'Male',
        imgUrl: '/images/pfp/law.png',
        price: 50,
        bio: "Trafalgar D. Water Law here. I'm the captain of the Heart Pirates, aiming to reshape the world. My life changed after the Battle of Marineford, and now I'm allied with the Straw Hats against the World Government. With my Devil Fruit powers and surgical skills, I'm ready to navigate the turbulent waters of the New World.",
        monday: "None",
        tuesday: "10am-3pm",
        wednesday: "2pm-7pm",
        thursday: "2pm-7pm",
        friday: "3pm-8pm",
        saturday: "None",
        sunday: "None"
    },
    {   firstName: 'God',
        lastName: 'Ussop',
        location: 'Cape Town, Africa',
        activity: 'Archery',
        sex: 'Male',
        imgUrl: '/images/pfp/ussop.png',
        price: 50,
        bio: "Hey, it's Usopp, the sharpshooter and storyteller of the Straw Hat Pirates! Born in Syrup Village, I've always had a flair for exaggeration. I dream of becoming a brave warrior of the sea like my father. Joining the Straw Hats has been a wild journey, and with my trusty sniper skills, I'll contribute to our epic adventures!",
        monday: "10am-3pm",
        tuesday: "None",
        wednesday: "8am-12pm",
        thursday: "None",
        friday: "3pm-8pm",
        saturday: "7am-12pm",
        sunday: "None"
    },
    {   firstName: 'Nico',
        lastName: 'Robin',
        location: 'Moscow, Russia',
        activity: 'Handball',
        sex: 'Female',
        imgUrl: '/images/pfp/robin.png',
        price: 50,
        bio: "Hi, I'm Nico Robin, the archaeologist of the Straw Hat crew. Originally from Ohara, my dream is to uncover the Void Century's secrets. I've faced adversity due to my knowledge of the Poneglyphs, but with the Straw Hats, I've found a family that accepts me. Together, we journey to unlock the mysteries of the world.",
        monday: "None",
        tuesday: "1pm-6pm",
        wednesday: "None",
        thursday: "9am-2pm",
        friday: "None",
        saturday: "7am-3pm",
        sunday: "None"
    },
    {   firstName: 'Roronoa',
        lastName: 'Zoro',
        location: 'Tokyo, Japan',
        activity: 'Kendo',
        sex: 'Male',
        imgUrl: '/images/pfp/zoro.png',
        price: 50,
        bio: "Roronoa Zoro, the Straw Hats' swordsman. My dream? To become the world's greatest swordsman! Trained in the ways of Bushido, I wield three swords and follow the path of the sword faithfully. With Luffy and the crew, I'm navigating the Grand Line, ready to face any challenge head-on!",
        monday: "11am-4pm",
        tuesday: "10am-3pm",
        wednesday: "9am-3pm",
        thursday: "10am-4pm",
        friday: "8am-4pm",
        saturday: "None",
        sunday: "None"
    },
    {   firstName: 'Shanks',
        lastName: '',
        location: 'Great Britain',
        activity: 'Kendo',
        sex: 'Male',
        imgUrl: '/images/pfp/shanks.png',
        price: 50,
        bio: "Shanks here, the captain of the Red-Haired Pirates. Known for my easygoing nature and red hair, I've influenced Luffy and inspired him to become a pirate. I may have left the crew, but my presence continues to shape the world. Keep an eye out for the Red-Haired Pirates!",
        monday: "None",
        tuesday: "None",
        wednesday: "None",
        thursday: "None",
        friday: "None",
        saturday: "7am-10pm",
        sunday: "7am-10pm"
    },
    {   firstName: 'Monkey D.',
        lastName: 'Luffy',
        location: 'Santos, Brazil',
        activity: 'Boxing',
        sex: 'Male',
        imgUrl: '/images/pfp/luffy.png',
        price: 50,
        bio: "Yo, it's Monkey D. Luffy! I'm the fearless captain of the Straw Hat Pirates, aiming to become the Pirate King. I got my Gum-Gum Fruit powers, making me stretchy like rubber! With my loyal crew, we're sailing the Grand Line, searching for the One Piece. I'm all about freedom, nakama, and never backing down from a challenge!",
        monday: "7am-12pm",
        tuesday: "3pm-8pm",
        wednesday: "8am-1pm",
        thursday: "8am-1pm",
        friday: "None",
        saturday: "None",
        sunday: "2pm-8pm"
    },
    {   firstName: 'Itachi',
        lastName: 'Uchiha',
        location: 'Seto, Japan',
        activity: 'Tricking',
        sex: 'Male',
        imgUrl: '/images/pfp/itachi.png',
        price: 50,
        bio: "Itachi Uchiha, the enigmatic shinobi. Born in the Uchiha clan, my life took a dark turn for the sake of peace. Branded a traitor, I walked a painful path. My actions were to protect my brother, Sasuke, and the Hidden Leaf Village. My story is one of sacrifice, tragedy, and love.",
        monday: "9am-2pm",
        tuesday: "3pm-8pm",
        wednesday: "8am-1pm",
        thursday: "None",
        friday: "9am-4pm",
        saturday: "None",
        sunday: "None"
    },
    {   firstName: 'Ash',
        lastName: 'Ketchum',
        location: 'California, America',
        activity: 'Equestria',
        sex: 'Male',
        imgUrl: '/images/pfp/ash.png',
        price: 50,
        bio: "Hey, I'm Ash Ketchum! Traveling the world with my trusty Pikachu, I aim to become a Pokémon Master. From Pallet Town to the Alola region, I've caught 'em all and faced legendary battles. With my friends and Pokémon by my side, there's no challenge too big on the road to becoming a Pokémon Master!",
        monday: "10am-3pm",
        tuesday: "2pm-7pm",
        wednesday: "1pm-6pm",
        thursday: "None",
        friday: "7am-1pm",
        saturday: "None",
        sunday: "7am-1pm"
    },
    {   firstName: 'Naruto',
        lastName: 'Uzumaki',
        location: 'Seto, Japan',
        activity: 'Parkour',
        sex: 'Male',
        imgUrl: '/images/pfp/naruto.png',
        price: 50,
        bio: "Naruto Uzumaki, the ninja with a dream! Growing up as an orphan in the Hidden Leaf Village, I aimed to become the Hokage, earning the respect of my fellow villagers. With the Nine-Tails Fox sealed within me, my journey was tough, but with my never-give-up attitude, I've overcome countless challenges.",
        monday: "2pm-8pm",
        tuesday: "12pm-5pm",
        wednesday: "7am-12pm",
        thursday: "3pm-8pm",
        friday: "8am-3pm",
        saturday: "7am-12pm",
        sunday: "None"
    },
    {   firstName: 'Sakura',
        lastName: 'Haruno',
        location: 'Seto, Japan',
        activity: 'Kick Boxing',
        sex: 'Female',
        imgUrl: '/images/pfp/sakura.png',
        price: 50,
        bio: "Sakura Haruno, aspiring medical ninja. From my days as a genin with Team 7, my goal was to surpass my limits. Trained by Tsunade, I mastered medical jutsu and became a vital asset to the Hidden Leaf Village. My journey is one of personal growth, friendship, and loyalty.",
        monday: "7am-12pm",
        tuesday: "7am-12pm",
        wednesday: "7am-12pm",
        thursday: "7am-12pm",
        friday: "7am-12pm",
        saturday: "None",
        sunday: "None"
    }
];

export default accounts;